package JavaScriptProject.patches.templates

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the template with uuid = '8fa43427-3d8d-4ae9-83fb-8f54279b3a32' (id = 'JavaScriptProject_Template')
accordingly and delete the patch script.
*/
changeTemplate("8fa43427-3d8d-4ae9-83fb-8f54279b3a32") {
    check(name == "Template") {
        "Unexpected name: '$name'"
    }
    name = "BaseTemplate"
}
