package JavaScriptProject.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.ui.deleteBuildType

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, remove the buildType with uuid = 'JavaScriptProject_IE' (id = 'JavaScriptProject_IE')
from your code and delete the patch script.
*/
deleteBuildType("JavaScriptProject_IE")

